#!/usr/bin/ruby

if ARGV.size != 2
	print "Usage: ./generate <plugin name> <boost location>\n"
	exit
end

$plugin_name = ARGV[0]
$boost_inc = "-I"+ARGV[1]
if $boost_inc[-1] == '/'[0]
	$boost_inc += "include"
else
	$boost_inc += "/include"
end

File.open("Makefile","w+") do | file |
	f = File.open("Makefile.tpl")
	lines = f.readlines
	f.close
	lines.each do | line | 
		if line.include?("TARGET")
			line.gsub!("XXXX",$plugin_name);
		elsif line.include?("INCLUDE")
			line.gsub!("XXXX",$boost_inc);
			line.chomp!
			line << " -I..\n"
		end
		file << line
	end
end

File.open("template.cpp") do | src |
	File.open($plugin_name+".cpp","w+") do | dst | 
		dst << src.read
	end
end
